# Generated by Django 5.2.3 on 2025-06-23 07:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermanentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='随机生成的 Token 值', max_length=64, unique=True)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Token 创建时间')),
                ('last_used', models.DateTimeField(blank=True, help_text='最后一次使用时间', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '长期 Token',
                'verbose_name_plural': '长期 Token',
                'ordering': ['-add_time'],
            },
        ),
    ]
