# Generated by Django 5.1.4 on 2025-05-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DividendRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dividend_date', models.DateField(verbose_name='分红公告日期')),
                ('plan', models.CharField(help_text='分红方案(每10股)', max_length=100, verbose_name='分红方案(每10股)')),
                ('status', models.CharField(help_text='分红进度', max_length=20, verbose_name='进度')),
                ('ex_dividend_date', models.CharField(blank=True, max_length=20, null=True, verbose_name='除权除息日')),
                ('register_date', models.CharField(blank=True, max_length=20, null=True, verbose_name='股权登记日')),
                ('listing_date', models.CharField(blank=True, max_length=20, null=True, verbose_name='红股上市日')),
                ('detail', models.CharField(blank=True, max_length=20, null=True, verbose_name='查看详细')),
                ('bonus_stock', models.CharField(blank=True, max_length=20, null=True, verbose_name='送股(股)')),
                ('transfer_stock', models.CharField(blank=True, max_length=20, null=True, verbose_name='转增(股)')),
                ('dividend_amount', models.CharField(blank=True, max_length=20, null=True, verbose_name='派息(税前)(元)')),
            ],
            options={
                'verbose_name': '分红记录',
                'verbose_name_plural': '分红记录',
            },
        ),
    ]
