# Generated by Django 5.2.1 on 2025-06-17 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DividendRecord',
            new_name='Dividend',
        ),
    ]
