# Generated by Django 5.2.1 on 2025-06-18 07:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_rename_dividendrecord_dividend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dividend',
            options={'verbose_name': 'Dividend', 'verbose_name_plural': 'Dividends'},
        ),
        migrations.RemoveField(
            model_name='dividend',
            name='bonus_stock',
        ),
        migrations.RemoveField(
            model_name='dividend',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='dividend',
            name='dividend_amount',
        ),
        migrations.RemoveField(
            model_name='dividend',
            name='dividend_date',
        ),
        migrations.RemoveField(
            model_name='dividend',
            name='listing_date',
        ),
        migrations.RemoveField(
            model_name='dividend',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='dividend',
            name='register_date',
        ),
        migrations.RemoveField(
            model_name='dividend',
            name='status',
        ),
        migrations.RemoveField(
            model_name='dividend',
            name='transfer_stock',
        ),
        migrations.AddField(
            model_name='dividend',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='dividend',
            name='announcement_date',
            field=models.DateField(blank=True, null=True, verbose_name='公告日期'),
        ),
        migrations.AddField(
            model_name='dividend',
            name='dividend_before_tax',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='派息(税前)(元)'),
        ),
        migrations.AddField(
            model_name='dividend',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='派息日'),
        ),
        migrations.AddField(
            model_name='dividend',
            name='stock_code',
            field=models.CharField(max_length=20, null=True, verbose_name='股票代码'),
        ),
        migrations.AddField(
            model_name='dividend',
            name='stock_name',
            field=models.CharField(max_length=100, null=True, verbose_name='股票名称'),
        ),
        migrations.AddField(
            model_name='dividend',
            name='stock_type',
            field=models.CharField(choices=[('A股', 'H股')], default='A股', max_length=10, verbose_name='股票类型'),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='ex_dividend_date',
            field=models.DateField(blank=True, null=True, verbose_name='除权除息日'),
        ),
    ]
