# Generated by Django 5.2.1 on 2025-06-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_dividend_options_remove_dividend_bonus_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividend',
            name='dividend_before_tax',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='派息(税前)(元)'),
        ),
    ]
