# Generated by Django 5.2.1 on 2025-06-17 01:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifycode',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='smsverifycode',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='add_time',
            field=models.DateField(default=django.utils.timezone.now, help_text='添加时间', verbose_name='添加时间'),
        ),
    ]
