#!/usr/bin/env python
# encoding: utf-8

router_datas = [
    {
        "router_id": 2000,
        "sub_router": None,
        "path": "/user",
        "component": "layout",
        "redirect": "/user/manage",
        "hidden": 0,
        "name": "userManage",
        "title": "user",
        "icon": "personnel",
    },
    {
        "router_id": 2001,
        "sub_router": 2000,
        "path": "/user/manage",
        "component": "user-manage",
        "redirect": None,
        "hidden": 0,
        "name": None,
        "title": "userManage",
        "icon": "personnel-manage",
    },
    {
        "router_id": 2002,
        "sub_router": 2000,
        "path": "/user/info/:id",
        "component": "user-info",
        "redirect": None,
        "hidden": True,
        "name": None,
        "title": "userInfo",
        "icon": None,
    },
    {
        "router_id": 2003,
        "sub_router": 2000,
        "path": "/user/import",
        "component": "import",
        "redirect": None,
        "hidden": False,
        "name": "import",
        "title": "excelImport",
        "icon": None,
    },
    {
        "router_id": 2004,
        "sub_router": 2000,
        "path": "/user/role",
        "component": "role-list",
        "redirect": None,
        "hidden": 0,
        "name": None,
        "title": "roleManage",
        "icon": "role",
    },
    {
        "router_id": 2005,
        "sub_router": 2000,
        "path": "/user/permission",
        "component": "permission-list",
        "redirect": None,
        "hidden": 0,
        "name": None,
        "title": "permissionManage",
        "icon": "permission",
    },
    # 文章
    {
        "router_id": 3000,
        "sub_router": None,
        "path": "/article",
        "component": "layout",
        "redirect": "/article/ranking",
        "hidden": 0,
        "name": "articleRanking",
        "title": "record",
        "icon": "article",
    },
    {
        "router_id": 3001,
        "sub_router": 3000,
        "path": "/article/ranking",
        "component": "article-ranking",
        "redirect": "/article/ranking",
        "hidden": 0,
        "name": "articleRanking",
        "title": "recordRanking",
        "icon": "article-ranking",
    },
    {
        "router_id": 3002,
        "sub_router": 3000,
        "path": "/article/:id",
        "component": "article-detail",
        "redirect": None,
        "hidden": True,
        "name": None,
        "title": "recordDetail",
        "icon": None,
    },
    {
        "router_id": 3003,
        "sub_router": 3000,
        "path": "/article/create",
        "component": "article-create",
        "redirect": None,
        "hidden": 0,
        "name": None,
        "title": "recordCreate",
        "icon": "article-create",
    },
    {
        "router_id": 3004,
        "sub_router": 3000,
        "path": "/article/editor/:id",
        "component": "article-create",
        "redirect": None,
        "hidden": True,
        "name": None,
        "title": "recordEditor",
        "icon": "article-create",
    },
    # 分红管理
    {
        "router_id": 4000,
        "sub_router": None,
        "path": "/deividend",
        "component": "layout",
        "redirect": "/dividend/ranking",
        "hidden": 0,
        "name": "articleRanking",
        "title": "record",
        "icon": "article",
    },
    {
        "router_id": 4001,
        "sub_router": 4000,
        "path": "/deividend/ranking",
        "component": "deividend-ranking",
        "redirect": "/deividend/ranking",
        "hidden": 0,
        "name": "deividendRanking",
        "title": "deividendRanking",
        "icon": "deividend-ranking",
    },
    {
        "router_id": 4002,
        "sub_router": 4000,
        "path": "/deividend/:id",
        "component": "deividend-detail",
        "redirect": None,
        "hidden": True,
        "name": None,
        "title": "deividendDetail",
        "icon": None,
    },
    {
        "router_id": 4003,
        "sub_router": 4000,
        "path": "/deividend/create",
        "component": "deividend-create",
        "redirect": None,
        "hidden": 0,
        "name": None,
        "title": "deividendCreate",
        "icon": "deividend-create",
    },
    {
        "router_id": 4004,
        "sub_router": 4000,
        "path": "/deividend/editor/:id",
        "component": "deividend-create",
        "redirect": None,
        "hidden": True,
        "name": None,
        "title": "deividendEditor",
        "icon": "deividend-create",
    },
    # Finance Management
    {
        "router_id": 5000,
        "sub_router": None,
        "path": "/finance",
        "component": "layout",
        "redirect": "/finance/dividend",
        "hidden": 0,
        "name": "financeManage",
        "title": "finance",
        "icon": "finance",
    },
    {
        "router_id": 5001,
        "sub_router": 5000,
        "path": "/finance/dividend",
        "component": "finance-dividend",
        "redirect": "/finance/dividend",
        "hidden": 0,
        "name": "dividendList",
        "title": "dividendList",
        "icon": "dividend",
    },
    {
        "router_id": 5002,
        "sub_router": 5000,
        "path": "/finance/dividend/:id",
        "component": "finance-dividend-detail",
        "redirect": None,
        "hidden": True,
        "name": None,
        "title": "dividendDetail",
        "icon": None,
    },
    {
        "router_id": 5003,
        "sub_router": 5000,
        "path": "/finance/dividend/create",
        "component": "finance-dividend-create",
        "redirect": None,
        "hidden": 0,
        "name": None,
        "title": "dividendCreate",
        "icon": "dividend-create",
    },
    {
        "router_id": 5004,
        "sub_router": 5000,
        "path": "/finance/dividend/editor/:id",
        "component": "finance-dividend-create",
        "redirect": None,
        "hidden": True,
        "name": None,
        "title": "dividendEditor",
        "icon": "dividend-create",
    },
]
